layout_spectrum: 0.1145687
typography_spectrum: 0.3566308
color:
  saturation: 0.749104
  brandStrength: 0.9253839
  lightness: 0.7562724
  rhythmicContrast: 0.3612074
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: 'Thorington Construction Consultancy '
